"""initial schema

Revision ID: 854dd171a78a
Revises: 
Create Date: 2026-05-18 12:15:42.951762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '854dd171a78a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('apply_to', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('vendor_hint', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_created_at', 'templates', ['created_at'], unique=False)
    op.create_index('ix_templates_model_id', 'templates', ['model_id'], unique=False)
    op.create_index('ix_templates_vendor_hint', 'templates', ['vendor_hint'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_file_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('ix_documents_template_id', 'documents', ['template_id'], unique=False)
    op.create_table('template_aggregation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('bounding_regions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_template_aggregation_rules_template_id_name', 'template_aggregation_rules', ['template_id', 'name'], unique=False)
    op.create_table('template_field_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('bounding_regions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hint', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('aliases_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_template_field_rules_template_id_name', 'template_field_rules', ['template_id', 'name'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_regions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_user_added', sa.Boolean(), nullable=False),
    sa.Column('aggregation_config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_fields_document_id_name', 'extracted_fields', ['document_id', 'name'], unique=False)
    op.create_table('extracted_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('bounding_regions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cells_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_tables_document_id_index', 'extracted_tables', ['document_id', 'index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extracted_tables_document_id_index', table_name='extracted_tables')
    op.drop_table('extracted_tables')
    op.drop_index('ix_extracted_fields_document_id_name', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index('ix_template_field_rules_template_id_name', table_name='template_field_rules')
    op.drop_table('template_field_rules')
    op.drop_index('ix_template_aggregation_rules_template_id_name', table_name='template_aggregation_rules')
    op.drop_table('template_aggregation_rules')
    op.drop_index('ix_documents_template_id', table_name='documents')
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_templates_vendor_hint', table_name='templates')
    op.drop_index('ix_templates_model_id', table_name='templates')
    op.drop_index('ix_templates_created_at', table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
