apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parsely-api.fullname" . }}-config
  labels:
    {{- include "parsely-api.labels" . | nindent 4 }}
data:
  AZURE_DI_ENDPOINT: {{ .Values.config.azureDiEndpoint | quote }}
  AZURE_BLOB_CONTAINER: {{ .Values.config.azureBlobContainer | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
